# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  nixpkgs.config.permittedInsecurePackages = [
    "broadcom-sta-6.30.223.271-59-6.12.74"
  ];
  nixpkgs.config.allowUnfreePackages = [ "broadcom-sta" ];
  configurations.nixos.marin.module =
    { lib, config, ... }:
    {
      #imports = [
      #  (modulesPath + "/installer/scan/not-detected.nix")
      #];

      boot = {
        initrd.availableKernelModules = [
          "xhci_pci"
          "ahci"
          "usbhid"
          "usb_storage"
          "sd_mod"
          "sdhci_pci"
        ];
        # initrd.kernelModules = [];
        kernelModules = [
          "kvm-intel"
          "wl"
        ];
        extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
      };

      fileSystems = {
        "/" = {
          device = "/dev/disk/by-uuid/c2c80df4-eb6e-446f-97ba-008f494c3817";
          fsType = "btrfs";
          options = [ "subvol=@" ];
        };

        "/home" = {
          device = "/dev/disk/by-uuid/c2c80df4-eb6e-446f-97ba-008f494c3817";
          fsType = "btrfs";
          options = [ "subvol=@home" ];
        };

        "/boot" = {
          device = "/dev/disk/by-uuid/7BA8-ACBD";
          fsType = "vfat";
          options = [
            "fmask=0022"
            "dmask=0022"
          ];
        };
      };

      swapDevices = [ { device = "/swap/swapfile"; } ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp3s0f0.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
