{
  imports = [
    ./settings.nix
    ./keys.nix
    ./plugs/lsp/lsp.nix
    ./plugs/lsp/conform.nix
    ./plugs/lsp/none-ls.nix
    ./plugs/lsp/cmp.nix
    ./plugs/filetypes/latex.nix
    ./plugs/ui/lualine.nix
    ./plugs/ui/staline.nix
    ./plugs/ui/bufferline.nix
    ./plugs/ui/lazygit.nix
    #./plugs/ui/telescope.nix
    ./plugs/ui/noice.nix
    ./plugs/ui/goyo.nix
    ./plugs/ui/obsidian.nix
  ];
}
