{
  imports = [
    ./settings.nix
    ./keys.nix
    ./plugs/lsp/lsp.nix
    ./plugs/lsp/conform.nix
    ./plugs/lsp/none-ls.nix
    ./plugs/lsp/cmp.nix
    ./plugs/filetypes/latex.nix
    ./plugs/ui/lualine.nix
    ./plugs/ui/staline.nix
    ./plugs/ui/bufferline.nix
    ./plugs/utils/lazygit.nix
    ./plugs/ui/noice.nix
    ./plugs/ui/notify.nix
    ./plugs/utils/whichkey.nix
    ./plugs/utils/telescope.nix
    ./plugs/ui/goyo.nix
    ./plugs/ui/nvim-tree.nix
    ./plugs/utils/obsidian.nix
    ./plugs/utils/autopair.nix
    ./plugs/utils/comment.nix
    ./plugs/utils/ibl.nix
    ./plugs/ui/toggleterm.nix
    ./plugs/ui/alpha.nix
    ./plugs/lsp/treesitter/treesitter.nix
  ];
}
