name: Flake Check
on: [push, pull_request, workflow_dispatch]
jobs:
  check:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run Nix flake check
      - name: Check nix flake
        run: nix flake check
